GTTCATACTGTCGTTGTGTC
=========================================
TATTGGTCCCAGACTTCAAG
=========================================
CTCACATTTATAAAAACCCT
=========================================
TTTATAATATAATCTGTCTC
=========================================
GACACAACGACAGTATGAAC
=========================================
TTTTTTTTTTTTTTTTTTTT
=========================================
TGTGTGTGTGTGTGTGTGTG
=========================================
GAGACAGATTATATTATAAA
=========================================
TTTTTAAAGATGGCTACAGA